import './docs.css'

type Section = { title: string; body: string; callout?: { title: string; body: string; warning?: boolean }; code?: string; flow?: string[] }
type Page = { group: string; path: string; title: string; description: string; sections: Section[] }

const PAGES: Page[] = [
  { group: 'Start', path: 'start/introduction', title: 'Welcome to NimFuel', description: 'NimFuel lets a Nimiq Pay user complete a Polygon USDT transfer when they have USDT but no POL for gas.', sections: [{ title: 'The problem it solves', body: 'A Polygon transaction needs POL for gas. When your Nimiq Pay EVM wallet holds USDT but no POL, that transfer cannot normally be sent.' }, { title: 'The simple idea', body: 'You approve the USDT transfer, pay NimFuel’s displayed cost in NIM, and NimFuel’s relayer supplies POL to submit the already-authorized Polygon transaction.' }, { title: 'What NimFuel does not do', body: 'It is not a wallet, bridge, swap app, or a way to move arbitrary assets. The current product is one Polygon USDT transfer flow inside Nimiq Pay.' }] },
  { group: 'Start', path: 'start/why-nimfuel', title: 'Why use NimFuel?', description: 'Use the NIM rail that still works when the Polygon gas rail is blocked.', sections: [{ title: 'Two rails in one wallet session', body: 'Nimiq Pay exposes a NIM account and an EVM account. Missing POL blocks the EVM transfer, while the NIM account can still make the payment needed to unlock it.' }, { title: 'The outcome', body: 'You do not have to leave the flow to acquire POL before sending your supported USDT transfer.' }] },
  { group: 'Start', path: 'start/how-it-works', title: 'How NimFuel works', description: 'One approved transfer, one NIM payment, and one verified Polygon result.', sections: [{ title: 'The path', body: 'NimFuel checks the wallet before asking you to approve anything.', flow: ['Check your Nimiq Pay wallet, Polygon network, USDT, and POL.', 'Choose the USDT recipient and amount, then sign the exact authorization.', 'Review and pay the order-specific NIM amount shown in Nimiq Pay.', 'NimFuel verifies the NIM payment, relays with POL, and verifies the Polygon receipt.'] }, { title: 'A result is only shown after verification', body: 'A wallet prompt or a submitted hash is not final success. NimFuel waits for the intended USDT state change in the Polygon receipt.' }] },
  { group: 'Start', path: 'start/try-nimfuel', title: 'Try NimFuel', description: 'Use a small real Polygon USDT transfer from Nimiq Pay.', sections: [{ title: 'Before you start', body: 'Use Nimiq Pay with Polygon selected, a supported USDT balance, and a NIM balance large enough for the quote. The recipient address must be a valid Polygon address.' }, { title: 'Run the flow', body: 'Open NimFuel, run wallet checks, enter a recipient and amount, sign the USDT authorization, then pay the exact NIM amount and reference shown. Do not change either value in the wallet prompt.' }, { title: 'After payment', body: 'Verify the NIM payment, then relay the paid order. Keep the order reference until the Polygon receipt is verified.' }] },
  { group: 'Using NimFuel', path: 'using-nimfuel/check-wallet', title: 'Check your wallet', description: 'NimFuel reads the state needed for a safe transfer before it prepares a quote.', sections: [{ title: 'What the checks cover', body: 'Nimiq SDK availability, your NIM account, consensus, EVM provider and account, Polygon chain 137, POL balance, USDT balance, and USDT metadata.' }, { title: 'Expected zero-POL state', body: 'A zero POL balance is the situation NimFuel is designed for. You still need enough USDT for the transfer and enough NIM for the quoted payment.' }] },
  { group: 'Using NimFuel', path: 'using-nimfuel/send-usdt', title: 'Send USDT', description: 'Choose the exact Polygon recipient and USDT amount you want to send.', sections: [{ title: 'Choose carefully', body: 'The recipient and amount are bound into the authorization. Check the address before you sign. A paid order cannot be changed to a different recipient or amount.' }, { title: 'Flexible amounts', body: 'The amount is entered by you and validated against the current policy and your token balance. NimFuel does not require one fixed test amount.' }] },
  { group: 'Using NimFuel', path: 'using-nimfuel/pay-with-nim', title: 'Pay with NIM', description: 'The NIM payment is tied to one order and is checked independently.', sections: [{ title: 'Pay the exact amount', body: 'NimFuel shows a NIM amount, recipient, and unique reference. Pay exactly those values through Nimiq Pay.' }, { title: 'Why the reference matters', body: 'The unique reference lets the backend match a payment to only one order and prevents the same payment from being used again.' }, { title: 'Wait for confirmation', body: 'The payment must be included and independently checked before Polygon fulfillment is unlocked.' }] },
  { group: 'Using NimFuel', path: 'using-nimfuel/transaction-progress', title: 'Track transaction progress', description: 'The order page shows where your action is in the verified lifecycle.', sections: [{ title: 'Typical progress', body: 'You will see an order created, NIM payment awaiting confirmation, NIM payment confirmed, Polygon relay submitted, and finally fulfilled.' }, { title: 'If a receipt is pending', body: 'A submitted Polygon hash can take time to be included. Keep the same order open or return through Order history. Do not pay a second NIM order for the same authorization.' }] },
  { group: 'Using NimFuel', path: 'using-nimfuel/order-history', title: 'Use order history', description: 'Return to a previous action after a refresh or an interrupted session.', sections: [{ title: 'Durable records', body: 'NimFuel stores orders in its durable order store and loads recent records for the connected EVM address.' }, { title: 'What to look for', body: 'Each record includes the USDT amount, current state, time, and a shortened order ID. Open the matching order to review its payment and relay proof.' }] },
  { group: 'Using NimFuel', path: 'using-nimfuel/recovery', title: 'Recover an interrupted order', description: 'Keep the same order reference when something does not finish normally.', sections: [{ title: 'Do not pay twice', body: 'If the NIM payment was submitted, return to that order and use Verify NIM payment again after inclusion. A matching payment is consumed by only one order.' }, { title: 'Relay retry', body: 'A paid order with a failed relay may require a fresh authorization for the original recipient and amount. Retry limits protect the order from repeated broadcasts.' }, { title: 'Support and refunds', body: 'If an order reaches recovery, keep its reference. The operator can review the verified order and follow the documented refund process when eligible.' }] },
  { group: 'Architecture', path: 'architecture/dual-rail-model', title: 'The dual-rail model', description: 'NimFuel connects Nimiq’s native payment rail to a blocked Polygon action.', sections: [{ title: 'NIM rail', body: 'The NIM account pays the displayed order cost and carries the order reference.' }, { title: 'Polygon rail', body: 'The EVM account signs the USDT authorization. The relayer supplies POL and submits the action only after the corresponding NIM payment is verified.' }] },
  { group: 'Architecture', path: 'architecture/authorization', title: 'USDT authorization', description: 'The user signs the transfer authority. NimFuel does not receive the user’s private key.', sections: [{ title: 'What is bound', body: 'The signature binds the recipient, USDT amount, token, Polygon chain, user nonce, and deadline.' }, { title: 'Server validation', body: 'Before quoting and relaying, the server validates the signature and reads the relevant live token state. The relayer then submits that user-authorized action.' }] },
  { group: 'Architecture', path: 'architecture/order-lifecycle', title: 'Order lifecycle', description: 'A durable order joins an authorization, a NIM payment, and a Polygon receipt.', sections: [{ title: 'Lifecycle', body: 'Orders move through creation, NIM payment verification, relay execution, and receipt verification. A successful order is FULFILLED.' }, { title: 'Durability', body: 'Payment and relay facts are persisted so refreshes and service restarts do not turn an already-paid order into a new charge.' }] },
  { group: 'Architecture', path: 'architecture/relayer', title: 'The Polygon relayer', description: 'The relayer has POL and submits a validated paid USDT action.', sections: [{ title: 'What it pays for', body: 'The relayer pays Polygon network gas. It does not fund the user’s wallet with POL as part of the normal flow.' }, { title: 'What it cannot change', body: 'It is limited by the signed authorization. It cannot substitute another recipient, amount, token, chain, nonce, or deadline.' }] },
  { group: 'Architecture', path: 'architecture/verification', title: 'Independent verification', description: 'NimFuel checks both payment rails before it calls an order complete.', sections: [{ title: 'NIM verification', body: 'The backend verifies the NIM transaction against the configured recipient, exact amount, order reference, and confirmation state.' }, { title: 'Polygon verification', body: 'The backend checks the transaction receipt and verifies the intended USDT transfer and authorization nonce change before marking the order fulfilled.' }] },
  { group: 'Reference', path: 'reference/supported-assets', title: 'Supported assets', description: 'The current user flow supports one token transfer and one payment asset.', sections: [{ title: 'Polygon USDT', body: 'The EVM action is a Polygon USDT transfer using the configured native Polygon USDT contract with 6 decimals.' }, { title: 'NIM', body: 'NIM pays the quoted gas and service cost for the order. The quote is created from current gas and market-price inputs.' }] },
  { group: 'Reference', path: 'reference/supported-networks', title: 'Supported networks', description: 'NimFuel currently operates on Polygon for the USDT action.', sections: [{ title: 'Polygon', body: 'The current EVM flow uses Polygon mainnet, chain ID 137. Its native gas asset is POL.' }, { title: 'Nimiq Pay', body: 'Nimiq Pay provides the native NIM payment rail and the injected EVM provider used for the Polygon authorization.' }] },
  { group: 'Reference', path: 'reference/fees', title: 'Fees and quotes', description: 'Every order shows its exact NIM payment before you approve it.', sections: [{ title: 'How a quote is made', body: 'NimFuel estimates Polygon gas for the authorized transfer, reads price inputs, applies the configured service policy, and displays the resulting NIM payment.' }, { title: 'Quote expiry', body: 'Quotes are short lived. If a quote expires before an order is created, prepare a fresh one. A paid order keeps its own recorded payment amount.' }] },
  { group: 'Reference', path: 'reference/order-states', title: 'Order states', description: 'Order states describe what has been verified, not just what was requested.', sections: [{ title: 'Key states', body: 'AWAITING_NIM_PAYMENT means payment is still required. NIM_PAYMENT_CONFIRMED unlocks relay. RELAY_SUBMITTED means Polygon inclusion is pending. FULFILLED means the receipt and intended state change were verified.' }, { title: 'Recovery states', body: 'RELAY_FAILED and RECOVERY_REQUIRED keep paid order evidence available for safe retry, review, or refund handling. REFUND_PENDING and REFUNDED are used by the operator-controlled refund path.' }] },
  { group: 'Reference', path: 'reference/deployment', title: 'Current deployment', description: 'NimFuel has a public frontend and a separate backend service.', sections: [{ title: 'Live surfaces', body: 'The frontend is available at nimfuel-app.onrender.com. The backend health summary is available at nimfuel-backend.onrender.com/health.' }, { title: 'Storage and operations', body: 'Orders use Neon PostgreSQL. The backend exposes public health summaries and protected operational detail for the operator.' }] },
  { group: 'Reference', path: 'reference/limitations', title: 'Current limitations', description: 'NimFuel keeps its first release narrow and explicit.', sections: [{ title: 'Current boundary', body: 'Only Polygon USDT transfers are supported. NimFuel does not support other tokens, chains, generic swaps, bridging, or automated wallet funding.' }, { title: 'Availability', body: 'A live relay depends on the relayer having POL, the payment and Polygon verification services being available, and safe market-price inputs.' }] },
  { group: 'Security', path: 'security/trust-model', title: 'Trust model', description: 'NimFuel separates user authority, payment verification, and relayer execution.', sections: [{ title: 'User and wallets', body: 'The user controls their NIM account and EVM authorization. NimFuel never receives the user’s wallet private key or seed phrase.' }, { title: 'Backend and relayer', body: 'The backend verifies payments, validates authorizations, persists orders, and operates the relayer. The relayer key stays server-side.' }] },
  { group: 'Security', path: 'security/authorization-boundaries', title: 'Authorization boundaries', description: 'The relayer can submit one signed action, not make a new transfer decision.', sections: [{ title: 'Signature scope', body: 'The user authorization fixes recipient, amount, token, chain, nonce, and deadline.' }, { title: 'Payment gate', body: 'A valid authorization alone does not unlock the relayer. The matching NIM payment must be independently verified first.' }] },
  { group: 'Security', path: 'security/replay-protection', title: 'Replay protection', description: 'Orders and authorizations are designed to avoid duplicate fulfillment.', sections: [{ title: 'One payment, one order', body: 'Nim payment hashes are matched to a unique order and cannot be reused to pay another one.' }, { title: 'Authorization nonce', body: 'The USDT authorization includes the user’s current nonce. A successful action advances it, preventing the same authorization from being replayed.' }] },
  { group: 'Security', path: 'security/recovery', title: 'Failure and recovery guarantees', description: 'A paid failure remains visible and recoverable rather than being silently treated as success.', sections: [{ title: 'Verified outcomes only', body: 'NimFuel does not mark an order fulfilled until it verifies the Polygon receipt and intended USDT state change.' }, { title: 'Retry and refund handling', body: 'Retries stay connected to the same paid order and are capped. Eligible paid recovery orders can enter an operator-controlled refund flow that is independently verified before REFUNDED is recorded.' }] },
  { group: 'Security', path: 'security/emergency-controls', title: 'Emergency controls', description: 'The operator can stop new relay work when a dependency or safety condition requires it.', sections: [{ title: 'Relay safety pause', body: 'When the safety pause is active, NimFuel rejects new relay flow actions instead of continuing with a known unsafe condition.' }, { title: 'Live broadcast switch', body: 'Live Polygon broadcast is separately controlled. Operators can disable it while keeping order and proof records available for review.' }] },
  { group: 'Security', path: 'security/privacy', title: 'Privacy', description: 'NimFuel uses public blockchain rails and does not promise transaction privacy.', sections: [{ title: 'Public information', body: 'NIM and Polygon transactions, token transfers, addresses, timestamps, and the order-specific payment reference can be observable on their respective networks.' }, { title: 'Private information', body: 'Private keys, seed phrases, relayer credentials, database credentials, and provider keys must remain outside the browser and repository.' }] },
  { group: 'Proof', path: 'proof/live-deployment', title: 'Live deployment', description: 'The hosted NimFuel flow uses a public frontend, native Node backend, and Neon order storage.', sections: [{ title: 'Where to inspect it', body: 'Open the live Mini App at https://nimfuel-app.onrender.com and the health summary at https://nimfuel-backend.onrender.com/health.' }, { title: 'Evidence boundary', body: 'A health response proves dependency status at that time. It does not by itself prove that a user-authorized wallet transaction succeeded.' }] },
  { group: 'Proof', path: 'proof/verified-transactions', title: 'Verified transactions', description: 'NimFuel has recorded completed Polygon USDT relay receipts from the live flow.', sections: [{ title: 'Recent verified relay', body: 'Polygon transaction 0xfa195a2b96427762d1abf80a9c307c71138ac8308d205c1bffeb4455fbb8e2d9 completed successfully in block 94074074.' }, { title: 'What was verified', body: 'The matching order was fulfilled after the NIM payment, exact USDT transfer, authorization nonce advance, relayer gas payment, and receipt status were verified.' }, { title: 'Open the receipt', body: 'Use PolygonScan to inspect the public transaction: https://polygonscan.com/tx/0xfa195a2b96427762d1abf80a9c307c71138ac8308d205c1bffeb4455fbb8e2d9' }] },
  { group: 'Proof', path: 'proof/zero-pol-example', title: 'A zero-POL example', description: 'The proof target is a USDT action succeeding without the user first acquiring POL.', sections: [{ title: 'Observed result', body: 'For the verified transaction above, the sender’s Polygon POL balance was checked as zero after the relay. The relayer, not the user, paid the transaction gas.' }, { title: 'What this proves', body: 'The supported USDT transfer completed through the NimFuel flow even though the user did not need to hold POL for that action.' }] },
  { group: 'Help', path: 'help/troubleshooting', title: 'Troubleshooting', description: 'Use the current order state to choose the safe next step.', sections: [{ title: 'Wallet check fails', body: 'Confirm you are inside Nimiq Pay, the EVM provider is available, and Polygon is selected. Re-run the checks after correcting the wallet state.' }, { title: 'Payment does not verify yet', body: 'Wait for the NIM transaction to be included, then use Verify NIM payment again on the same order. Confirm the exact amount and reference were used.' }, { title: 'Relay is pending or failed', body: 'Keep the order reference and return through Order history. Do not create another payment for the same action. Follow the on-screen recovery state.' }] },
  { group: 'Help', path: 'help/faq', title: 'Frequently asked questions', description: 'Short answers for the normal NimFuel flow.', sections: [{ title: 'Do I need POL?', body: 'For the supported NimFuel transfer, the relayer supplies POL for gas after your NIM payment is verified.' }, { title: 'Why do I pay NIM?', body: 'NIM is the payment rail NimFuel uses to cover the quoted Polygon gas and configured service cost.' }, { title: 'Can I change a paid order?', body: 'No. Recipient and amount are part of the signed authorization and paid order. Create a new action after the current order is fulfilled, recovered, or refunded.' }, { title: 'Does NimFuel support other networks?', body: 'No. The current public flow is Polygon USDT only.' }] },
]

const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
const pageForPath = (path: string) => PAGES.find(page => `/docs/${page.path}` === path) || PAGES[0]
const href = (page: Page) => `/docs/${page.path}`
const slug = (title: string, index: number) => `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${index + 1}`

function navHtml(active: Page) {
  const groups = [...new Set(PAGES.map(page => page.group))]
  return groups.map(group => `<section class="nf-docs-nav-group"><p>${escape(group)}</p>${PAGES.filter(page => page.group === group).map(page => `<a class="${page.path === active.path ? 'is-active' : ''}" href="${href(page)}">${escape(page.title)}</a>`).join('')}</section>`).join('')
}

function sectionHtml(section: Section, index: number) {
  const id = slug(section.title, index)
  const flow = section.flow ? `<ol class="nf-docs-flow">${section.flow.map((step, stepIndex) => `<li><span>${String(stepIndex + 1).padStart(2, '0')}</span><p>${escape(step)}</p></li>`).join('')}</ol>` : ''
  const callout = section.callout ? `<aside class="nf-docs-callout ${section.callout.warning ? 'is-warning' : ''}"><strong>${escape(section.callout.title)}</strong><p>${escape(section.callout.body)}</p></aside>` : ''
  const code = section.code ? `<div class="nf-docs-code"><div><span>Example</span><button type="button" data-copy="${escape(section.code)}">Copy</button></div><pre><code>${escape(section.code)}</code></pre></div>` : ''
  return `<section id="${id}" class="nf-docs-section"><h2>${escape(section.title)}</h2><p>${escape(section.body)}</p>${flow}${callout}${code}</section>`
}

export function renderDocs(root: HTMLDivElement) {
  let active = pageForPath(window.location.pathname)
  const render = () => {
    active = pageForPath(window.location.pathname)
    const index = PAGES.indexOf(active)
    const previous = PAGES[index - 1]
    const next = PAGES[index + 1]
    const toc = active.sections.map((section, sectionIndex) => `<a href="#${slug(section.title, sectionIndex)}">${escape(section.title)}</a>`).join('')
    root.innerHTML = `<main class="nf-docs"><a class="nf-docs-skip" href="#docs-content">Skip to docs</a><header class="nf-docs-header"><a class="nf-docs-brand" href="/"><img src="/nimfuel-logo.png" alt="NimFuel"/><span><strong>NimFuel</strong><small>Help and documentation</small></span></a><label class="nf-docs-search"><span>Search</span><input id="nf-docs-search" placeholder="Search NimFuel docs" aria-label="Search NimFuel docs" autocomplete="off"/></label><nav><a href="/">Open app</a><a href="https://github.com/CryptoZephyr/NimFuel" target="_blank" rel="noreferrer">GitHub</a></nav><button class="nf-docs-menu" type="button" aria-expanded="false">Menu</button></header><div class="nf-docs-results" hidden></div><div class="nf-docs-layout"><aside class="nf-docs-sidebar"><nav aria-label="Documentation navigation">${navHtml(active)}</nav><p class="nf-docs-boundary">Current scope: Polygon USDT transfers paid for in NIM.</p></aside><article id="docs-content" class="nf-docs-content"><header class="nf-docs-lead"><p>${escape(active.group)}</p><h1>${escape(active.title)}</h1><p>${escape(active.description)}</p></header><details class="nf-docs-mobile-toc"><summary>On this page</summary><nav>${toc}</nav></details>${active.sections.map(sectionHtml).join('')}<nav class="nf-docs-pagination">${previous ? `<a href="${href(previous)}"><span>Previous</span><strong>${escape(previous.title)}</strong></a>` : '<span></span>'}${next ? `<a href="${href(next)}"><span>Next</span><strong>${escape(next.title)}</strong></a>` : '<span></span>'}</nav></article><aside class="nf-docs-on-page"><p>On this page</p><nav>${toc}</nav></aside></div></main>`
    bind()
    document.title = `${active.title} | NimFuel docs`
  }
  const navigate = (target: HTMLAnchorElement) => {
    const url = new URL(target.href)
    if (url.origin === window.location.origin && url.pathname.startsWith('/docs/')) { window.history.pushState({}, '', `${url.pathname}${url.hash}`); render(); window.scrollTo({ top: 0 }); return true }
    return false
  }
  const bind = () => {
    root.querySelectorAll<HTMLAnchorElement>('a[href]').forEach(link => link.addEventListener('click', event => { if (navigate(link)) event.preventDefault() }))
    root.querySelector<HTMLButtonElement>('.nf-docs-menu')?.addEventListener('click', event => { const button = event.currentTarget; const open = root.classList.toggle('nf-docs-menu-open'); button.setAttribute('aria-expanded', String(open)) })
    root.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(button => button.addEventListener('click', async () => { await navigator.clipboard.writeText(button.dataset.copy || ''); button.textContent = 'Copied'; window.setTimeout(() => { button.textContent = 'Copy' }, 1400) }))
    root.querySelector<HTMLInputElement>('#nf-docs-search')?.addEventListener('input', event => { const input = event.currentTarget; const query = input.value.trim().toLowerCase(); const results = root.querySelector<HTMLDivElement>('.nf-docs-results')!; const matches = query ? PAGES.filter(page => `${page.title} ${page.description} ${page.group}`.toLowerCase().includes(query)).slice(0, 8) : []; results.hidden = matches.length === 0; results.innerHTML = matches.map(page => `<a href="${href(page)}"><strong>${escape(page.title)}</strong><span>${escape(page.group)} · ${escape(page.description)}</span></a>`).join(''); results.querySelectorAll<HTMLAnchorElement>('a').forEach(link => link.addEventListener('click', event => { if (navigate(link)) event.preventDefault() })) })
  }
  window.addEventListener('popstate', () => { render(); window.scrollTo({ top: 0 }) })
  render()
}
